material-components/material-web

- scripts/bootstrap-unreleased.sh
- scripts/update-styling.sh
> Fix scripts by using `bash` explictitly

- README.md
- packages/button/README.md
- packages/checkbox/README.md
- packages/fab/README.md
- packages/icon/README.md
- packages/radio/README.md
- packages/ripple/README.md
- packages/switch/README.md
> Update Readme getting started

- packages/switch/mwc-switch.js
- test/unit/mwc-switch.test.js
I don't consider these tests or the API changes complete; I'm mostly just pushing this so that it isn't lost.
> [switch] Add basic tests and `disabled` property.

- README.md
- package-lock.json
- package.json
- scripts/watcher.js
Uses `node-watch` to watch for changes and run `npm run build`
It does too much, but I'm not sure how to do any incremental builds
Fixes #115
> Implement watcher

- packages/base/src/base-element.ts
- packages/checkbox/src/mwc-checkbox.ts
- packages/drawer/src/mwc-drawer.ts
- packages/formfield/src/mwc-formfield.ts
- packages/linear-progress/src/mwc-linear-progress.ts
- packages/radio/src/mwc-radio.ts
- packages/radio/src/selection-controller.ts
- packages/switch/src/mwc-switch.ts
- packages/tab-bar/src/mwc-tab-bar.ts
- packages/tab-indicator/src/mwc-tab-indicator.ts
- packages/tab-scroller/src/mwc-tab-scroller.ts
- packages/tab/src/mwc-tab.ts
- packages/top-app-bar/src/mwc-top-app-bar.ts
- Add `focusNative()` for Radio and SelectionController integration
Fixes #130
> Make all `@query` class fields protected

- packages/base/package.json
- packages/button/package.json
- packages/card/package.json
- packages/checkbox/package.json
- packages/chips/package.json
- packages/dialog/package.json
- packages/drawer/package.json
- packages/fab/package.json
- packages/formfield/package.json
- packages/icon-toggle/package.json
- packages/icon/package.json
- packages/linear-progress/package.json
- packages/list/package.json
- packages/menu/package.json
- packages/radio/package.json
- packages/ripple/package.json
- packages/ripple/src/ripple-directive.ts
- packages/select/package.json
- packages/slider/package.json
- packages/snackbar/package.json
- packages/switch/package.json
- packages/tab-bar/package.json
- packages/tab-indicator/package.json
- packages/tab-scroller/package.json
- packages/tab/package.json
- packages/textfield/package.json
- packages/top-app-bar/package.json
- packages/typography/package.json
Also make explicit dependencies on lit-html where needed
Fixes #132
> Update to lit-element 0.6.2

- packages/base/src/base-element.ts
- packages/button/src/mwc-button.ts
- packages/checkbox/src/mwc-checkbox.ts
- packages/drawer/src/mwc-drawer.ts
- packages/fab/src/mwc-fab.ts
- packages/formfield/src/mwc-formfield.ts
- packages/icon/src/mwc-icon.ts
- packages/linear-progress/src/mwc-linear-progress.ts
- packages/radio/src/mwc-radio.ts
- packages/radio/src/selection-controller.ts
- packages/ripple/src/mwc-ripple.ts
- packages/ripple/src/ripple-directive.ts
- packages/switch/src/mwc-switch.ts
- packages/tab-bar/src/mwc-tab-bar.ts
- packages/tab-indicator/src/mwc-tab-indicator.ts
- packages/tab-scroller/src/mwc-tab-scroller.ts
- packages/tab/src/mwc-tab.ts
- packages/top-app-bar/src/mwc-top-app-bar.ts
> Add explicit file endings when not using package main

- CHANGELOG.md
- demos/index.html
- packages/checkbox/src/mwc-checkbox.ts
- packages/drawer/src/mwc-drawer.ts
- packages/formfield/src/mwc-formfield.ts
- packages/radio/src/mwc-radio.ts
- packages/switch/src/mwc-switch.ts
- packages/tab-bar/src/mwc-tab-bar.ts
- packages/tab-scroller/src/mwc-tab-scroller.ts
- packages/tab/src/mwc-tab.ts
Add `@eventOptions({passive: true})` for interation handlers in
tab-scroller
Fixes #136
Fixes #149
> Use listener functions on the class

- packages/drawer/src/mwc-drawer.ts
- packages/icon-button/src/icon-button-base.ts
Fixes #191.
Note: Does not add list navigation integration because mwc-list component is not implemented.
> Drawer: Implement focus trapping

- packages/ripple/src/mwc-ripple.ts
> Ripple: update element after setting interaction node

- demos/tabs.html
- demos/tabs/rtl.html
- packages/tab/src/mwc-tab.scss
- packages/tab/src/mwc-tab.ts
Support TabBars/Tabs.
How: (1) detect and set the `dir` attribute on `mwc-tab`. (2) Override Sass declarations from mdc-tab to detect `dir` on the host element.
Fixes: #194
> TabBar: RTL support

- package-lock.json
- packages/button/package.json
- packages/checkbox/package.json
- packages/drawer/package.json
- packages/fab/package.json
- packages/formfield/package.json
- packages/icon-button/package.json
- packages/linear-progress/package.json
- packages/radio/package.json
- packages/radio/src/mwc-radio.ts
- packages/ripple/package.json
- packages/slider/package.json
- packages/snackbar/package.json
- packages/switch/package.json
- packages/tab-bar/package.json
- packages/tab-bar/src/mwc-tab-bar.ts
- packages/tab-indicator/package.json
- packages/tab-scroller/package.json
- packages/tab/package.json
- packages/tab/src/mwc-tab.ts
- packages/top-app-bar/package.json
- update components to mdc 0.44 (except tab-indicator/linear-progress for which the latest release is 0.43)
- update tab and tab-bar to work with the latest mdc. API changes in mdc: https://github.com/material-components/material-components-web/commit/2d352208ab8e5deb4a6116330c348d0447f008d9#diff-df09c0ed448f9f4fc1996e30d51e9921
- update radio to work with the latest mdc. API Changes in mdc: https://github.com/material-components/material-components-web/commit/476130efd32434e0491c97ef4de1a2643ce255bc#diff-59ed8c64b286edd1e8a21edeb1c32972
> Update to mdc 0.44

- CONTRIBUTING.md
The link based on:
@Polymer/lit-element/master/CONTRIBUTING.md
Thanks!
> Fix broken link in contribution docs. Closes #84

- demos/button.html
- packages/button/src/mwc-button.ts
Add trailing icon to button. Fixes #239 and #235.
> add trailing icon to button

- package-lock.json
- package.json
Verified webcomponentsjs v2.2.8 fixes https://github.com/material-components/material-components-web-components/issues/233 and https://github.com/material-components/material-components-web-components/issues/218
> Update webcomponentsjs to v2.2.8

- packages/ripple/src/mwc-ripple.ts
- test/unit/mwc-ripple.test.js
> ripple: Fix interactionNode property

- packages/button/src/mwc-button.scss
- packages/fab/src/mwc-fab.scss
- packages/icon/src/mwc-icon-host.scss
- packages/ripple/src/ripple-directive.ts
- packages/tab-indicator/src/mwc-tab-indicator.scss
- packages/tab/src/mwc-tab.scss
Add missing semicolon and standardize SASS import quote style
> Add missing semicolon and standardize SASS import quote style

- README.md
- no public export in index.js, provide correct filename
Thanks!
> Correct usage documentation in README. Closes #34

- demos/chips.html
replace leadingIcon with trailingIcon in trailing icon demo
> Fix typo in chips demo

- package-lock.json
- packages/base/package.json
- packages/tab-bar/src/mwc-tab-bar-base.ts
Use new getUpdateComplete method.
Must wait until https://github.com/Polymer/lit-element/pull/745 before merging.
> Use new getUpdateComplete method.

- packages/top-app-bar/src/mwc-top-app-bar-base.ts
Fix top-app-bar typings for getViewportScrollY
> Fix top-app-bar typings for getViewportScrollY

- karma.conf.js
- packages/tab/src/mwc-tab.ts
closes #276
There was already a unit test coverage for the bug, but the tests were not enabled for the tabs file. This enables the tabs tests and fixes the bug.
> fix(mwc-tab): DOMException The result must not have attributes

- packages/line-ripple/CHANGELOG.md
- packages/line-ripple/README.md
- packages/line-ripple/package.json
- packages/line-ripple/src/line-ripple-directive.ts
- packages/line-ripple/src/mwc-line-ripple.scss
- packages/line-ripple/tsconfig.json
- packages/textfield/package.json
- packages/textfield/src/mwc-textfield-base.ts
> Line ripple

- test/benchmark/bench-runner.html
- test/benchmark/button/test-basic.ts
- test/benchmark/checkbox/test-basic.ts
- test/benchmark/cli.ts
- test/benchmark/drawer/test-basic.ts
- test/benchmark/fab/test-basic.ts
- test/benchmark/formfield/test-basic.ts
- test/benchmark/helpers.ts
- test/benchmark/icon-button/test-basic.ts
- test/benchmark/icon/test-basic.ts
- test/benchmark/linear-progress/test-basic.ts
- test/benchmark/radio/test-basic.ts
- test/benchmark/ripple/test-basic.ts
- test/benchmark/slider/test-basic.ts
- test/benchmark/snackbar/test-basic.ts
- test/benchmark/switch/test-basic.ts
- test/benchmark/tab-bar/test-basic.ts
- test/benchmark/tab/test-basic.ts
- test/benchmark/top-app-bar/test-basic.ts
only add licenses to test files
CC @aomarks
> add licenses to tests

- packages/drawer/src/mwc-drawer-base.ts
Fix imports of inert and blocking-element polyfills.
> Fix imports of inert and blocking-element polyfills.

- packages/formfield/src/mwc-formfield-base.ts
- packages/tab-bar/src/mwc-tab-bar-base.ts
Same as https://github.com/material-components/material-components-web-components/pull/331, see there for more info.
> More workarounds for HTMLSlotElement and emitDecoratorMetadata bug

- demos/demo-component.css
- demos/index.html
- package-lock.json
We no longer auto-import fonts.
(Add &w=1 to the URL, all other changes are pure whitespace)
> Add font import to demo

- CHANGELOG.md
- packages/button/src/mwc-button.ts
- packages/checkbox/src/mwc-checkbox.ts
- packages/drawer/src/mwc-drawer.ts
- packages/fab/src/mwc-fab.ts
- packages/formfield/src/mwc-formfield.ts
- packages/icon-button/src/mwc-icon-button.ts
- packages/icon/src/mwc-icon.ts
- packages/linear-progress/src/mwc-linear-progress.ts
- packages/radio/src/mwc-radio.ts
- packages/ripple/src/mwc-ripple.ts
- packages/slider/src/mwc-slider.ts
- packages/snackbar/src/mwc-snackbar.ts
- packages/switch/src/mwc-switch.ts
- packages/tab-bar/src/mwc-tab-bar.ts
- packages/tab-indicator/src/mwc-tab-indicator.ts
- packages/tab-scroller/src/mwc-tab-scroller.ts
- packages/tab/src/mwc-tab.ts
- packages/top-app-bar/src/mwc-top-app-bar.ts
Unnecessary as of lit-element v0.6.5
Fixes #114
> Remove `as any` usage with `@customElement`

- CHANGELOG.md
- package-lock.json
- packages/drawer/package.json
Via https://github.com/WICG/inert/pull/129
> Bump inert polyfill to fix drawer IE bug

- packages/notched-outline/README.md
necessary for readme in textfield that defers to this for css props
> add css custom props table to readme

- packages/drawer/src/mwc-drawer-base.ts
- packages/radio/src/mwc-radio-base.ts
- packages/ripple/src/ripple-directive.ts
- packages/tab-bar/src/mwc-tab-bar-base.ts
- packages/textarea/src/mwc-textarea-base.ts
- packages/textarea/src/mwc-textarea.ts
- packages/textfield/src/mwc-textfield-base.ts
- packages/textfield/src/mwc-textfield.ts
> fixed lint & ran formatter

- karma.conf.js
> actually enable sauce launcher

- package-lock.json
- packages/tab-bar/src/mwc-tab-bar.scss
- packages/tab/src/mwc-tab.scss
Upstream http://cl/268767671. Add `--mdc-tab-stacked-height` CSS variable to control tab height.
> Add --mdc-tab-stacked-height CSS variable to control tab height

- packages/textarea/src/mwc-textarea-base.ts
- packages/textfield/src/mwc-textfield.scss
upstreaming fixes from cl/267202399
> Fix internal build

- CHANGELOG.md
- package-lock.json
- package.json
- packages/textarea/src/mwc-textarea-base.ts
- packages/textfield/src/mwc-textfield-base.ts
fixes #474
Can't test these changes with our current setup.
Benchmark results came up with creation being 0-3% faster for reasons unknown. On typing couldn't really be tested because we would need selenium or puppeteer to test. Changing values via JS showed inconclusive on change (though eyeballing a bit slower maybe?).
> update textfield value on input instead of change

- CHANGELOG.md
- packages/dialog/package.json
it's already in the tsconfig, but forgot to add it to package.json. Does this need to go in changelog?
> add missing dep to mwc-dialog

- packages/slider/package.json
- packages/slider/src/mwc-slider-base.ts
fixes #486.
Also cleaned up innerText implementation and cleaned up render function to look less ugly.
> update mwc-slider to MDC 4

- packages/radio/src/mwc-radio-base.ts
> Update mwc-radio to MDC 4

- CHANGELOG.md
> update changelog from internal

- packages/radio/src/mwc-radio.scss
> mwc-radio vertical alignment

- packages/button/src/mwc-button.scss
> Fix misaligned buttons with icons (#626)

- packages/textfield/README.md
- packages/textfield/src/mwc-textfield-base.ts
- packages/textfield/src/test/mwc-textfield.test.ts
fixes #660.
Adds outlined validation tests, adds warning in readme, fixes tpyos.
> Textfield validation outlined

- packages/base/src/elevation.scss
- packages/button/README.md
- packages/button/src/mwc-button.scss
- packages/dialog/README.md
- packages/dialog/src/mwc-dialog.scss
- packages/fab/README.md
- packages/fab/src/mwc-fab.scss
- packages/top-app-bar-fixed/README.md
- packages/top-app-bar/src/mwc-top-app-bar.scss
Added box-shadow custom props for:
* button
* dialog
* fab
* top-app-bar-fixed
> box-shadow custom props

- demos/button.html
- demos/card.html
- demos/checkbox.html
- demos/chips.html
- demos/dialog.html
- demos/drawer.html
- demos/drawer/drawer.js
- demos/fab.html
- demos/formfield.html
- demos/icon-button-toggle.html
- demos/icon-button.html
- demos/icon.html
- demos/linear-progress.html
- demos/menu.html
- demos/radio.html
- demos/ripple.html
- demos/select.html
- demos/slider.html
- demos/snackbar.html
- demos/switch.html
- demos/tabs.html
- demos/tabs/rtl.html
- demos/textarea.html
- demos/textfield.html
- demos/top-app-bar-fixed.html
- demos/top-app-bar.html
- demos/top-app-bars/fixed.html
- demos/top-app-bars/standard.html
fixes #700
checked that ie will now show the tabs. There are some bugs though. We should work on adding scuba tests for those failing cases
> remove es6 from demos

- .eslintrc.yaml
- package-lock.json
- package.json
- packages/base/src/elevation.scss
- packages/base/src/utils.ts
- packages/dialog/src/mwc-dialog-base.ts
- packages/drawer/src/mwc-drawer-base.ts
- packages/slider/src/mwc-slider-base.ts
- packages/snackbar/src/mwc-snackbar-base.ts
- packages/textarea/src/mwc-textarea.scss
- packages/textfield/src/mwc-textfield.scss
- packages/top-app-bar/src/mwc-top-app-bar.scss
mdc sass was migrated to modules. This needed an update to sass as well as sass-modularization of textfield, textarea, and top-app-bar.
internal investigation by sass team ongoing to see what's causing the issues in these elements
> fix sass build

- packages/textfield/README.md
Some weird copybara issue, not sure why. Hopefully this will fix.
> Remove comment that crept in via #815

- CHANGELOG.md
- demos/textarea.html
- demos/textfield.html
- packages/textarea/src/mwc-textarea-base.ts
- packages/textfield/src/mwc-textfield-base.ts
> Add end-aligned to textfields #818

- CHANGELOG.md
- packages/top-app-bar/src/mwc-top-app-bar-base-base.ts
> fix(top-app-bar): update listeners when scrollTarget changes #736

- CHANGELOG.md
- packages/textfield/src/mwc-textfield-base.ts
> feat(textfield): add inputmode

- packages/icon-button/src/mwc-icon-button.scss
> no pointer events on disabled icon button

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/new-task-template.md
Update templates for Bugs, Features, and Tasks
> Update issue templates

- packages/select/README.md
- packages/select/src/mwc-select.scss
fixes #869
Actually applies `--mdc-select-ink-color`
> Apply select ink color

- demos/menu.html
- packages/menu/README.md
Clarify documentation of anchor in menu
> docs(menu): Better document anchor

- packages/base/src/form-element.ts
- packages/button/src/mwc-button-base.ts
- packages/dialog/src/mwc-dialog-base.ts
- packages/drawer/src/mwc-drawer-base.ts
- packages/fab/src/mwc-fab-base.ts
- packages/formfield/src/mwc-formfield-base.ts
- packages/icon-button-toggle/src/mwc-icon-button-toggle.ts
- packages/list/src/mwc-check-list-item-base.ts
- packages/list/src/mwc-list-adapter.ts
- packages/list/src/mwc-list-base.ts
- packages/list/src/mwc-list-foundation.ts
- packages/list/src/mwc-list.ts
- packages/list/src/mwc-radio-list-item-base.ts
- packages/menu/src/mwc-menu-base.ts
- packages/menu/src/mwc-menu-surface-base.ts
- packages/menu/src/mwc-menu-surface.ts
- packages/menu/src/mwc-menu.ts
- packages/ripple/src/mwc-ripple-base.ts
- packages/select/src/mwc-select-base.ts
- packages/slider/src/mwc-slider-base.ts
- packages/snackbar/src/mwc-snackbar-base.ts
- packages/tab-indicator/src/mwc-tab-indicator-base.ts
- packages/tab/src/mwc-tab-base.ts
- packages/textarea/src/mwc-textarea-base.ts
- packages/textfield/src/mwc-textfield-base.ts
- packages/top-app-bar-fixed/src/mwc-top-app-bar-fixed.ts
- packages/top-app-bar/src/mwc-top-app-bar-base-base.ts
- packages/top-app-bar/src/mwc-top-app-bar-base.ts
This solves #926. 
It adds missing `.js` extension is import statement.
> added missing .js extension

- packages/select/src/test/mwc-select.test.ts
- test/src/util/helpers.ts
deflake IE select tests. Possible distribution race condition
fixes #944
> test(select): deflake IE select tests

- package.json
- test/src/benchmark/list-item/basic.ts
- test/src/benchmark/list/basic.ts
> perf(list): benchmarks for list and list-item

- demos/dialog.html
> fix(dialog): demo buttons open appropriate dialogs

- CHANGELOG.md
- demos/button.html
- demos/checkbox.html
- demos/chips.html
- demos/demo-component.css
- demos/demo-header.js
- demos/dialog.html
- demos/drawer.html
- demos/fab.html
- demos/formfield.html
- demos/icon-button-toggle.html
- demos/icon-button.html
- demos/icon.html
- demos/index.js
- demos/linear-progress.html
- demos/list.html
- demos/menu.html
- demos/radio.html
- demos/ripple.html
- demos/select.html
- demos/slider.html
- demos/snackbar.html
- demos/switch.html
- demos/tabs.html
- demos/textarea.html
- demos/textfield.html
- demos/top-app-bar-fixed.html
- demos/top-app-bar.html
- packages/list/src/mwc-list-base.ts
demos link to glitch source and the main index.html page is easier to edit and uses mwc-list and friends with correct aria roles
example:
I would also like to make a patch release to update the glitch
depends on #1021
> demo: demos use mwc components and link to glitch

- demos/switch.html
this has been an issue for a while and i continue to forget to fix it (already fixed it in glitch manually)
> demo(switch): add active switches to demos

- README.md
> docs: add my config for dev to contrib guide

- CHANGELOG.md
- packages/slider/src/mwc-slider-base.ts
- packages/slider/src/test/mwc-slider.test.ts
- test/src/util/helpers.ts
> fix(slider): min and max update UI correctly

- demos/list.html
- packages/list/README.md
- packages/list/package.json
- packages/list/src/mwc-check-list-item-base.ts
- packages/list/src/mwc-list-item-base.ts
- packages/list/src/mwc-list-item.scss
- packages/list/src/mwc-radio-list-item-base.ts
fixes #745
about 13-19% faster than `master` when selected but not `activated`. about 8-12% faster than `master` when initialized as `activated`.
not `activated` is 9-15% faster than `activated`.
> refactor(list): remove rippleNode for mwc-ripple

- test/src/benchmark/snackbar/test-basic.ts
Fix an issue caused by a refactor to snackbar. Could not be fixed internally. This will unblock a bunch of internal CLs
> fix(build): CI build caused by refactor snackbar

- CHANGELOG.md
- packages/list/src/mwc-list-item-base.ts
- packages/list/src/mwc-list-item.scss
fixes #1270
fixes #1271
fixes #1272
> fix(list): li aria roles and ripple & mobile press

- CHANGELOG.md
- packages/tab-bar/src/test/mwc-tab-bar.test.ts
- packages/tab/src/mwc-tab-base.ts
> fix(tabs): do not focus on init

- demos/linear-progress/index.html
> Fixed typo

- README.md
We need minimize bugs count. ;-)
> Add the badge for bugs to readme

- demos/button/index.html
- demos/checkbox/index.html
- demos/dialog/index.html
- demos/drawer/index.html
- demos/drawer_dismissible/index.html
- demos/drawer_modal/index.html
- demos/drawer_standard/index.html
- demos/drawer_standard_no_header/index.html
- demos/fab/index.html
- demos/formfield/index.html
- demos/icon-button-toggle/index.html
- demos/icon-button/index.html
- demos/icon/index.html
- demos/index.html
- demos/list/index.html
- demos/menu/index.html
- demos/radio/index.html
- demos/select/index.html
- demos/slider/index.html
- demos/snackbar/index.html
- demos/switch/index.html
- demos/tabs/index.html
- demos/tabs_rtl/index.html
- demos/textarea/index.html
- demos/textfield/index.html
- demos/top-app-bar-fixed/index.html
- demos/top-app-bar-fixed_iframe/index.html
- demos/top-app-bar/index.html
- demos/top-app-bar_iframe/index.html
This pr fixes all typos of `nomodlue` to `nomodule`
> find and replace all typos with `nomodlue`

- README.md
> Update the correct demo port

- CHANGELOG.md
- packages/icon-button/src/mwc-icon-button-base.ts
- packages/icon-button/src/mwc-icon-button.scss
Replace `ripple-directive` with lazy `mwc-ripple`
Related #894
Related #1054
> Refactor `mwc-icon-button` replace ripple with lazy mwc-ripple

- packages/switch/src/mwc-switch-base.ts
- packages/switch/src/mwc-switch.scss
Refactor switch replace ripple directive with lazy `mwc-ripple`
Related #894
Related #1054
> Refactor switch replace ripple directive with lazy mwc-ripple

- package.json
- packages/icon-button-toggle/src/mwc-icon-button-toggle-base.ts
see:
https://github.com/material-components/material-components-web-components/runs/900346141?check_suite_focus=true
> ci(format:check): make format check output more useful

- packages/checkbox/src/mwc-checkbox-base.ts
Fix ripple deactivate on checkbox when releasing outside of checkbox
> Fix ripple deactivate on checkbox when releasing outside of checkbox

- demos/circular-progress/index.html
- demos/circular-progress/index.js
They seemed to fit well in the same demo page.
> demo(circular-progress): add four color variant

- packages/select/README.md
> docs(select): remove refs to multi selection

- packages/base/package.json
- packages/button/package.json
- packages/checkbox/package.json
- packages/circular-progress-four-color/package.json
- packages/circular-progress/package.json
- packages/dialog/package.json
- packages/drawer/package.json
- packages/fab/package.json
- packages/floating-label/package.json
- packages/formfield/package.json
- packages/icon-button-toggle/package.json
- packages/icon-button/package.json
- packages/line-ripple/package.json
- packages/linear-progress/package.json
- packages/list/package.json
- packages/menu/package.json
- packages/notched-outline/package.json
- packages/radio/package.json
- packages/ripple/package.json
- packages/select/package.json
- packages/slider/package.json
- packages/snackbar/package.json
- packages/switch/package.json
- packages/tab-bar/package.json
- packages/tab-indicator/package.json
- packages/tab-scroller/package.json
- packages/tab/package.json
- packages/textfield/package.json
- packages/top-app-bar-fixed/package.json
- packages/top-app-bar/package.json
Reverts material-components/material-components-web-components#1734
> Revert "Auto bump MDC Web deps to 8.0.0-canary.a1c65593d.0"

- packages/checkbox/test/mwc-checkbox.test.ts
This is just normalising the tests and adding a few assertions to match with what i did last time i reworked all the tests (added a "factory" kind of pattern).
> mwc-checkbox: normalise tests

- package-lock.json
- package.json
- tsconfig.json
enforces removed copybara rule
> chore: update lit-analyzer & lint rules

- LICENSE
> docs: Update LICENSE file to be exact copy of apache license

- CHANGELOG.md
- package-lock.json
- package.json
> Upgrade to typescript 4.0.3

- CHANGELOG.md
- packages/slider/mwc-slider-base.ts
- packages/slider/test/mwc-slider.test.ts
(chore) [Slider] Add support for `aria-label` and `aria-labelledby`
> (chore) [Slider] Add support for `aria-label` and `aria-labelledby`

- packages/list/mwc-list-base.ts
- packages/menu/mwc-menu-base.ts
- packages/select/mwc-select-base.ts
- packages/tab-bar/mwc-tab-bar-base.ts
- packages/textfield/mwc-textfield-base.ts
2.5.0 has a compatibility change to lit 1 for lit 2. Since we were mid-migration to Lit 2, we doubled up on these efforts and caused an infinite loop.
cc: @dfreedm @bicknellr
> fix: compat between lit-element 2.4.0 & 2.5.0

- packages/switch/tsconfig.json
Needed for https://github.com/material-components/material-components-web-components/pull/2545
> chore(switch): include deprecated files in switch build

- .github/workflows/tests.yml
- Check format in parallel with running unit tests
- Remove unused "lint" job
> Run format check in parallel

- demos/slider/index.html
- demos/slider/index.js
- scripts/bump-all-mdc-web-deps.ts
does not need copybara. external only
> chore(slider): allow dependency updating and update demo

- test/tsconfig.json
Needed to merge https://github.com/material-components/material-components-web-components/pull/2591
> chore: exclude deprecated switch from tests

- README.md
Optimize font loading. This seems to be the new default proposed on Google Fonts as well.
> Warm up connection for Google fonts

- .github/workflows/tests.yml
Removed external format checks to stay in sync with internal format.
> build: Remove external format checks

- .github/workflows/tests.yml
Formatting is checked internally
> Remove format checks on commits

- packages/button/README.md
Add the missing `fullwidth` property
> Add fullwidth property to Properties section

- package-lock.json
- package.json
since saucelabs has been removed.
remove saucelabs dependencies from karma.
> [tests] remove saucelabs dependencies

- CHANGELOG.md
- components/checkbox/lib/_checkbox.scss
- components/checkbox/md-checkbox_test.ts
- components/focus/test/screenshot_test.ts
- components/switch/lib/_switch-theme.scss
- components/switch/lib/_switch.scss
- components/switch/lib/switch.ts
- components/tabs/tab_bar/lib/primary-tab-bar.ts
- components/tabs/tab_bar/lib/secondary-tab-bar.ts
- components/tabs/tab_bar/lib/tab-bar.ts
- components/testing/harness.ts
- components/testing/templates.ts
chore: internal change
FUTURE_COPYBARA_INTEGRATE_REVIEW=https://github.com/material-components/material-web/pull/3403 from material-components:release 36f752a51c3d6d6ec9867fdbf4da700e05f38af0
> chore: internal change

- packages/menu/mwc-menu-base.ts
- packages/menu/mwc-menu-surface-base.ts
- packages/select/mwc-select-base.ts
> Refactor select menu for subclassing

- package-lock.json
- package.json
This will be needed before https://github.com/material-components/material-web/pull/4108 can build
> chore: install safevalues for AOM delegation shim

- testing/environment.ts
I believe this should work too, right @asyncLiz ?
> chore: update environment.ts

- linearprogress/lib/_linear-progress.scss
- linearprogress/lib/linear-progress.ts
> fix(linearprogress): rename fourColors to fourColor

- menu/menu.ts
Modify the label name of md-sub-menu-item in example.
**from**
```html
</md-sub-menu>
```
**to**
```html
</md-sub-menu-item>
```
> chore(menu): modify the label name of md-sub-menu-item in example

- .github/workflows/build-catalog.yml
- .github/workflows/deploy-catalog.yml
~Requires #4380 and #4381 to merge before it builds~
Fixes b/285197169
> build(ci/catalog): gh actions to build & delploy catalog

- catalog/src/components/theme-changer.ts
- catalog/src/utils/apply-theme-string.ts
- catalog/src/utils/theme.ts
My first contribution to the catalog.
> chore(catalog): refactoring some types

- radio/lib/single-selection-controller.ts
- radio/radio_test.ts
> fix(dialog): fire a change event when using arrow keys

- .github/workflows/firebase-hosting-pull-request.yml
This might not be the right name but no good way to test
> ci: ignore release please bot

- catalog/package.json
- package-lock.json
- package.json
synchronize TS version with components and bump wireit across the board
> build: bump wireit versions and catalog ts version

- slider/internal/slider.ts
> chore(slider): fix internal typos

- field/internal/_content.scss
fixes https://github.com/material-components/material-web/issues/5230
> fix(text-field): wrap text in textarea

- list/internal/listitem/_list-item.scss
fixes https://github.com/material-components/material-web/issues/5219
> fix(list-item): hide headline overflow and fix width

- chips/internal/_shared.scss
- chips/internal/chip.ts
fixes https://github.com/material-components/material-web/issues/5196
> fix(chip): disabled attribute prevents click event

- tabs/internal/tabs.ts
Fixes #5297
All necessary pieces were already there, they just need to be exposed.
> feat(tabs): support setting active-tab-index attribute on md-tabs

- docs/intro.md
Changes a leftover png to a webp so an image is displayed correctly in the docs.
> docs: change .png to .webp

- list/internal/listitem/list-item.ts
fixes https://github.com/material-components/material-web/issues/5705
> fix(list): list item click() not working
