packages/all.js, test/unit/mwc-button.test.js, test/unit/mwc-checkbox.test.js, test/unit/mwc-ripple.test.js
- `mwc-fab` is now in its own package.
- `mwc-ripple-surface` doesn't seem to exist as a separate component anymore.
- Adds `async` to a few test functions that were using `await`.
There are still some left over uncaught errors that happen when running the tests that I'm still looking into. They don't cause the tests to fail though, so they must be async.
=> Fix dependency references and tests.

demos/button.html, demos/fab.html, packages/button/mwc-button.js, packages/fab/mwc-fab.js, test/unit/mwc-button.test.js, test/unit/mwc-fab.test.js
- Are the tests too brittle by they way they look into the internals to find elements?
- I added `label` as a property of fab because users will want to label the button in FABs with text that's more descriptive than just the icon name.
- Tests for the FAB are split into a different file.
=> Extra tests for button, FAB. Add `label` property to FAB.

package-lock.json, package.json
The elements in these packages depend on @polymer/lit-element@^0.5.2, which depend on lit-html@^0.10.0:
https://github.com/Polymer/lit-element/blob/v0.5.2/package.json#L39 (7f01cbb07645248b035fd824e5db62dd96bafaf8)
lit-html@0.10.1 includes changes which make it incompatible with shadycss <1.3.0:
https://github.com/Polymer/lit-html/commit/4dea332e7bc6153e749265323c7df85d4813757e
webcomponentsjs@2.0.1 is the first to build with shadycss >=1.3.0:
https://github.com/webcomponents/webcomponentsjs/blob/v2.0.0/package-lock.json#L1293 (df225f93b54f1944318931b770bc5c6b2d5de98d)
https://github.com/webcomponents/webcomponentsjs/blob/v2.0.1/package-lock.json#L1287 (c6a97da5621b2f40fe8046c8dd66febb5b0c8120)
cc @justinfagnani
=> Update @webcomponents/webcomponentsjs to v2.0.1

package-lock.json, package.json, scripts/watcher.js, tsconfig.json
- Run `build` first before watching
- Make sure node-watch dependency is installed
- Only rebuild style files if they change, significantly speeding up builds
=> Improve `npm run watch`

packages/base/component-element.js
afterNextRender have been remove from utils.js in favor of element renderComplete
=> use renderComplete

packages/select/mwc-select.js, packages/textfield/mwc-textfield.js, test/unit/mwc-switch.test.js
utils.js doesn't export or even implement that function any more, trying to import it just causes errors
=> remove imports of afterNextRender (unused)

package-lock.json, package.json
The flatmap-stream has been removed from NPM:
https://www.npmjs.com/package/flatmap-stream
With this change the project installs locally.
Thanks!
```bash
npm i
npm ERR! code E404
npm ERR! 404 Not Found: flatmap-stream@0.1.0
```
```bash
├─┬ npm-run-all@4.1.3
│ ├── ansi-styles@3.2.1
│ ├─┬ chalk@2.4.1
│ │ └── supports-color@5.5.0
│ ├─┬ cross-spawn@6.0.5
│ │ └── nice-try@1.0.5
│ ├── memorystream@0.3.1
│ ├─┬ ps-tree@1.1.0
│ │ └─┬ event-stream@3.3.6
│ │   ├── flatmap-stream@0.1.0
│ │   ├── from@0.1.7
│ │   ├── map-stream@0.0.7
│ │   ├── pause-stream@0.0.11
│ │   └── stream-combiner@0.2.2
```
=> Update npm-run-all version to fix flatmap-stream dependency

packages/ripple/src/ripple-directive.ts
In 144213a5403731775e3e92a6c9841f0227e5120a packages got dependencies updated for lit-html 0.13. However, there was a [breaking change](https://github.com/Polymer/lit-html/releases/tag/v0.13.0) in lit-html 0.13 that was not taken into account:
- [Breaking] Directives are now defined by passing the entire directive factory function to directive(). (https://github.com/Polymer/lit-html/pull/562)
This PR will update the Ripple directive to use the new format.
CC @azakus
=> Fix ripple directive for lit-html 0.13

packages/base/src/base-element.ts, packages/button/package.json, packages/button/src/mwc-button.ts, packages/checkbox/package.json, packages/drawer/package.json, packages/drawer/src/mwc-drawer.ts, packages/fab/package.json, packages/fab/src/mwc-fab.ts, packages/formfield/package.json, packages/formfield/src/mwc-formfield.ts, packages/icon/package.json, packages/icon/src/mwc-icon.ts, packages/linear-progress/package.json, packages/radio/package.json, packages/ripple/package.json, packages/ripple/src/mwc-ripple.ts, packages/slider/package.json, packages/slider/src/mwc-slider.ts, packages/snackbar/package.json, packages/switch/package.json, packages/tab-bar/package.json, packages/tab-indicator/package.json, packages/tab-indicator/src/mwc-tab-indicator.ts, packages/tab-scroller/package.json, packages/tab/package.json, packages/tab/src/mwc-tab.ts, packages/top-app-bar/package.json, packages/top-app-bar/src/mwc-top-app-bar.ts, sass-template.tmpl
mwc-base exports everything needed by the majority of elements.
This will reduce maintenance on updating lit versions.
=> Minimize direct imports of lit-html and lit-element

demos/drawer/dismissible.html, demos/drawer/drawer.css, demos/drawer/modal.html, demos/drawer/standard.html, packages/drawer/src/mwc-drawer.scss, packages/drawer/src/mwc-drawer.ts
Idea for adding .mdc-drawer-app-content styling to app content next to drawers.
With this solution, all app content would be light dom for the mwc-drawer component. I added `slot="appContent"` to a container div in the demos, but of course one could add `slot="appContent"` to each sibling of the drawer content.
We should probably discuss this solution and potential alternatives.
Fixes #193
=> Drawer: Slot app content

packages/drawer/src/mwc-drawer.ts
The focus trap behavior regressed when the `appContent` slot was introduced (Let's get integration tests). Frankie is right in #221: When the mdcRoot is added to $blockingElements, only the siblings of the parents are made inert. Since the `aside`, `scrim`, and `appContent` are all siblings, we have to get away with directly setting `inert` on appContent. We retain the $blockingElements usage for cases in which there are further ancestors.
Fixes: #221
=> Drawer: Fix focus trap for new appContent slot

packages/drawer/src/mwc-drawer.ts
I raised [this issue](https://github.com/material-components/material-components-web/issues/4268) in material-web-components regarding the ordering of `releaseFocus` and `restoreFocus` for the mdc-drawer component. The fix for this issue was [merged](https://github.com/material-components/material-components-web/pull/4304), and finally released as part of [v.0.44](https://github.com/material-components/material-components-web/releases/tag/v0.44.0).
Now that we're up to date with v.0.44, this PR implements the releasing of focus in the proper lifecycle method (`releaseFocus`, not `restoreFocus`).
=> Drawer: Use fixed focus trap lifecycle

demos/top-app-bar.html, packages/top-app-bar/src/mwc-top-app-bar.ts
Remove "extra row" functionality from top app bar.
fixes: #197
=> TopAppBar: remove extra row

packages/button/src/mwc-button.ts
Add mdc-button__label class. Fixes #235.
=> add mdc-button__label class

demos/top-app-bar.html, packages/top-app-bar/src/mwc-top-app-bar.scss, packages/top-app-bar/src/mwc-top-app-bar.ts
Allow the title to be centered on the Top App Bar. The option is exposed as a boolean property on the host called `centerTitle`. Open to suggestions on this API choice.
_Note: This is not a built-in feature from the material spec._ That being said, centered titles are featured in some of the Material custom theme case studies. (see "Rally Theme" from [Top App Bar spec](https://material.io/design/components/app-bars-top.html#theming))
closes #189
=> TopAppBar: Add centered title option

packages/button/src/mwc-button.scss, packages/button/src/mwc-button.ts
Disable pointer events when `<mwc-button>` is disabled.
Approach copied from how Polymer implements similar functionality: https://github.com/PolymerElements/iron-behaviors/blob/master/iron-control-state.js#L76-L95
Fixes #148
=> Disable pointer events when button is disabled

package-lock.json, package.json, packages/base/src/form-element.ts, test/unit/mwc-switch.test.js
Summary: Listen for and re-dispatch `change` events in `FormElement`s. The differences between the old and new event are that the new event will be untrusted and will have `src-element` and `target` equal to the custom element.
Fixes #63
=> Forward `change` events out of form elements

packages/button/src/mwc-button.scss
`flex:1` does not seem to behave the same in IE11 as other browsers, but `flex:auto` works consistently here. Confirmed with internal screenshot tests.
=> Fix <mwc-button> width in IE11

packages/formfield/package.json
This should fix the error shown @ [https://www.webcomponents.org/element/@material/mwc-formfield](https://www.webcomponents.org/element/@material/mwc-formfield).
---
<h3 class="style-scope catalog-error">Error  - 15</h3>
<h1 class="page-title style-scope catalog-error">Unable to process element</h1>
<h2 class="page-subtitle style-scope catalog-error">{"message": "No github URL associated with package", "code": 15}</h2>
=> add repository url to mdc-form-field package

packages/base/package.json, packages/button/package.json, packages/checkbox/package.json, packages/drawer/package.json, packages/fab/package.json, packages/formfield/package.json, packages/icon-button/package.json, packages/icon/package.json, packages/linear-progress/package.json, packages/radio/package.json, packages/ripple/package.json, packages/slider/package.json, packages/snackbar/package.json, packages/switch/package.json, packages/tab-bar/package.json, packages/tab-indicator/package.json, packages/tab-scroller/package.json, packages/tab/package.json, packages/top-app-bar/package.json
This is the new way to mark a package in a monorepo.
See [repository.directory](https://docs.npmjs.com/files/package.json#repository) property in `package.json`.
In a future release of `npmjs.com` this will allow to link directly to a package in a monorepo.
https://docs.npmjs.com/files/package.json#repository  
https://github.com/npm/rfcs/blob/latest/implemented/0010-monorepo-subdirectory-declaration.md
Related https://github.com/material-components/material-components-web/pull/4897
Related https://github.com/material-components/material-components-web-react/pull/975
=> chore: add `repository.directory` in `package.json` for all packages

.gitignore, .vscode/settings.json, README.md, package-lock.json, package.json, test/benchmark/bench-runner.html, test/benchmark/button/test-basic.ts, test/benchmark/checkbox/test-basic.ts, test/benchmark/cli.ts, test/benchmark/drawer/test-basic.ts, test/benchmark/fab/test-basic.ts, test/benchmark/formfield/test-basic.ts, test/benchmark/helpers.ts, test/benchmark/icon-button/test-basic.ts, test/benchmark/icon/test-basic.ts, test/benchmark/linear-progress/test-basic.ts, test/benchmark/radio/test-basic.ts, test/benchmark/ripple/test-basic.ts, test/benchmark/slider/test-basic.ts, test/benchmark/snackbar/test-basic.ts, test/benchmark/switch/test-basic.ts, test/benchmark/tab-bar/test-basic.ts, test/benchmark/tab/test-basic.ts, test/benchmark/top-app-bar/test-basic.ts, test/tsconfig-node.json, test/tsconfig.json
You can now benchmark! You just have to build the test files and then run them with node.
fixes: #300.
e.g. `npm run build:tests && npm run test:bench` or just run via node after build `node test/benchmark/cli.js`. It has a `--help` page for common flags to pass.
What I run to run it on my workstation is
`npm run test:bench -- --remote http://localhost:4444/wd/hub`.
* benchmarks written in TS
* added a `test/tsconfig.json` for browser target
* CLI written in TS
* added a separate `test/tsconfig-node.json` for node target
* TS compiles to the same location instead of a separate lib folder
* This is because I have a testing harness at `test/benchmark/bench-runner.html` that relies on relative urls
* I did not want the harness to live in a `lib` folder which is specifically not-ignored by …
=> Tachometer benchmarking

CHANGELOG.md, packages/button/src/mwc-button.ts, packages/fab/src/mwc-fab.ts, packages/icon-button/src/mwc-icon-button.ts, packages/icon/src/mwc-icon.ts
We don't want to force users to load the Material Icons font in any particular way. For example, users may want to load Roboto and Icons with one request (e.g. `https://fonts.googleapis.com/css?family=Roboto|Roboto+Mono|Material+Icons`), or they might want to host their own version.
The `mwc-icon-font` module can still be imported by the user (which adds a `<link>` to the head) if they want this easy option.
Fixes #195 
Fixes #90
=> Don't automatically import Material Icons font.

test/benchmark/helpers.ts, test/benchmark/snackbar/test-basic.ts
There was a problem where our tachometer implementation using RAF would not paint the elements onto the page / do style recalculation before measuring.
I instead switched from using the lit element `test-fixture` and instead simply use `lit-html`'s render method and checking the first child and awaiting `updateComplete` + forcing style recalc w/ `offsetWidth`.
If there is no first child with `updateComplete` we just simply await a RAF.
Also changed the test harness interface to take an object of options rather than params.
fixes #312.
=> Fix tachometer

packages/ripple/src/ripple-directive.ts
Declare the ripple property so that MWC elements validate with runem's lit analyzer / ide plugin.
=> Declare the ripple property so that MWC elements validate with runem's lit analyzer / ide plugin.

.eslintrc.yaml, package-lock.json, package.json, packages/tab/src/mwc-tab-base.ts
This sorts the problem that the base classes aren't being linted at the min.
The linter works by looking for a customElement decorator or JSDoc, of which the base classes have none. So i've gone ahead and added the setting in to specify `BaseElement` as a custom element base class.
~weird one here is that `firstUpdated` needs to pass on the `PropertyValues` parameter to `super`. should we just.. import that type from lit or what? the tab package doesn't have lit as a dependency so that seems not-so-right to do.~
nvm seems baseelement has no change param
cc @aomarks
=> update eslint plugin

.gitignore, packages/textfield/src/character-counter/mwc-character-counter-directive.ts, packages/textfield/src/mwc-textarea-base.ts, packages/textfield/src/mwc-textfield-base.ts, packages/textfield/tsconfig.json
we were using a textfield internal component which I pulled out. Here are perf results where "bundle" is their component bundled in vs "test-basic" being the new directive implementation
=> Implement Character counter

packages/fab/src/mwc-fab-base.ts, packages/slider/src/mwc-slider-base.ts, packages/tab/src/mwc-tab-base.ts
they were unstable and clang-format would break lint. These are stable and pass lint
=> some formatter fixes that don't fail with lint

CHANGELOG.md, packages/tab-bar/src/mwc-tab-bar.scss
If an `<mwc-tab-bar>`'s container doesn't fit the bar with all its tabs, then the tabs should not overflow the container, and should automatically scroll horizontally so that the selected tab is displayed, like this:
This is what we get in in Chrome 76. But in Firefox 68, we get this:
Changing the style to `:host { display: block; }` makes the behavior match. There seems to be an inconsistency between Firefox and Chrome here -- maybe a Firefox bug? Changing `display` to any of: `unset`, `block`, or `inline` works, but `flex-inline` has the same problem.
I'm also wondering why we put `display:flex` on the host anyway? My (very possibly wrong) understanding was that `display:flex` is equivalent to `display:block` in terms of the layout of the flex container *itself* (where `display: …
=> Fix <mwc-tab-bar> layout issue in Firefox

CHANGELOG.md, packages/icon/src/_mwc-icon.scss
IE11 requires `font-feature-settings: 'liga'` to be turned on to render ligatures.
I also synchronized this styling generally to exactly match the recommendations at https://google.github.io/material-design-icons/#icon-images-for-the-web
Fixes https://github.com/material-components/material-components-web-components/issues/122
=> Fix IE11 icon rendering in <mwc-icon>

CHANGELOG.md, demos/snackbar.html, packages/snackbar/src/mwc-snackbar.scss
Adds rules which apply the correct default color and icon size to `<mwc-button>` and `<mwc-icon-button>` in the `action` and `dismiss` slots.
Adds `--mdc-snackbar-action-color` CSS custom property to override the default color of the action button text.
Before:
After:
=> Fix <mwc-snackbar> default action/dismiss button styles.

package-lock.json, package.json, scripts/print-css-custom-properties.js
Prints selector, property, and fallback value for the CSS Custom
Properties in a Sass file
Example usage:
```
./scripts/print-css-custom-properties.js packages/snackbar/src/mwc-snackbar.scss
```
Example output:
```css
slot[name=action]::slotted(mwc-button) { --mdc-theme-primary: var(--mdc-snackbar-action-color, #bb86fc) }
```
=> Print CSS Custom Properties of a Sass file

CHANGELOG.md, packages/snackbar/src/mwc-snackbar-base.ts
This bit me in testing, and turns out at least one other user has already encountered it. I can imagine wanting to create the element and immediately open it might be a common enough pattern that we should support this.
Fixes https://github.com/material-components/material-components-web-components/issues/308
=> Allow <mwc-button> open method to be called before firstUpdated

CHANGELOG.md, demos/icon-button.html, packages/icon-button/src/icon-button-base.ts, packages/icon-button/src/mwc-icon-button.scss, test/unit/mwc-icon-button.test.js
Refactor `<mwc-icon-button>` to have slots, allowing SVG and image icons.
Icon must have `slot="onIcon"`attribute for non-toggling buttons, and an additional Icon with `slot="offIcon"` for toggling buttons
Example:
```html
<mwc-icon-button>
</mwc-icon-button>
```
TODO for PR:
Fixes #156
=> Refactor icon-button to accept SVG or image icons

.gitignore, demos/demo-component.css, package.json, scripts/static-urlify-readme-images.ts, scripts/tsconfig.json
This way we don't need to publish images in our NPM tarballs (they're already in our `.npmignore` files), but the READMEs will still render with images on npmjs.com, webcomponents.org, etc.
It resolves master to a SHA, and uses that in a raw.githubusercontent.com URL, so that if we change or move images files around, any given version of the README published to NPM won't be
affected.
I made this a prepack script, so that it runs automatically before we publish. (We would not commit those changes, since on GitHub it makes more sense to just the relative path like always).
For example, here's what it did to the FAB README:
Also threw in a small fix to our demo CSS Roboto font weights (my mistake from earlier PR).
=> Script to rewrite README images as permanent URLs

CHANGELOG.md, packages/radio/src/mwc-radio-base.ts, test/unit/mwc-radio.test.js
Previously, we didn't trigger the `SelectionController` (the class that synchronizes radio button groups separated by a shadow root) when the checked property was set, so the previously checked radio in a group was not unchecked when a new one was checked.
This was more complicated than just triggering it from the existing property `@observer`, because that gives us batched async changes (via the `UpdatingElement` updated callback), so we can't reconstruct the order of checked sets correctly. Replaces the observer with a setter that can handle this synchronously.
=> Fix broken checked property in <mwc-radio>

packages/radio/src/mwc-radio-base.ts, test/unit/mwc-radio.test.js
Previously, we did not use the `SelectionController` class when we were not using native shadow roots, because we could rely on the native behavior to manage selection groups for us.
However, since the native `<input>` is not stamped until the async first update, groups were not being managed correctly immediately after construction.
Now, we always use a `SelectionController`. It's probably a little less efficient when we don't have native shadow, and it would be possible to e.g. force an early render to make this work, but I don't think the extra complexity is worth it.
Also expanded the unit test coverage.
=> Use SelectionController in <mwc-radio> even without native shadow

packages/ripple/src/mwc-ripple-base.ts
Node properties should be attribute:false anyway.
=> Fix lit-analyzer warning about property without attribute data.

packages/button/src/mwc-button.scss
This regressed in the button README PR (https://github.com/material-components/material-components-web-components/pull/366). This reverts that. We want the inner button to expand to the size of the host, so that the user can specify the width of the button.
Found because it broke our internal screenshot test which checks that the button grows when the user sets host width.
=> Make inner button element stretch to width of host

packages/icon-button-toggle/README.md, packages/top-app-bar-fixed/README.md, packages/top-app-bar/README.md
This simplifies some automated internal documentation transformations.
=> Standardize format (HTTPS and trailing slash) of MWC links

CHANGELOG.md, packages/floating-label/src/mwc-floating-label-directive.ts, packages/line-ripple/src/mwc-line-ripple-directive.ts, packages/textfield/package.json, packages/textfield/src/character-counter/mwc-character-counter-directive.ts, packages/textfield/src/mwc-textfield-base.ts
- **INTERNAL BREAKING** Changed interface to:
- LineRipple: foundation -> lineRippleFoundation
- CharCounter: foundation -> characterCounterFoundation
- FloatingLabel: foundation -> floatingLabelFoundation
- **INTERNAL BREAKING** added following properties to global `Element` interface
- lineRippleFoundation?: MDCLineRippleFoundation
- characterCounterFoundation?: MDCTextFieldCharacterCounterFoundation
- floatingLabelFoundationtion?: MDCFloatingLabelFoundation
- Renamed textfield's directive applications
- Removed implicit any's in textfield caused by ValidityState
related #454
=> Changes to Textfield, line-ripple, and floating-label to build internally

CHANGELOG.md, packages/drawer/package.json
Fixes https://github.com/material-components/material-components-web-components/issues/257
=> Bump wicg-inert version to ensure module field exists for bundling.

CHANGELOG.md, packages/base/package.json, packages/base/src/form-element.ts, packages/button/src/mwc-button-base.ts, packages/textfield/src/mwc-textfield-base.ts, test/src/unit/mwc-button.test.ts, test/src/util/helpers.ts
- mwc-button
- Added custom focus and blur functions that cause ripple
- mwc-textfield
- Focus function now focuses the native input and activates the caret
- Blur appropriately blurs the input
=> Fix focus button textfield

packages/textfield/src/mwc-textfield-base.ts, test/src/unit/mwc-textfield.test.ts
pretty simple one
fixes #461.
fixes #68.
LMK if you're up for merging it. also if you think we need to dispatch an event or anything alongside calling `select()` (as thats what focus/blur methods do).
cc @azakus @e111077
=> add select() to text fields

CHANGELOG.md, packages/textarea/src/mwc-textarea-base.ts, packages/textfield/src/mwc-textfield-base.ts, test/src/unit/mwc-textfield.test.ts
fixes #467 
removed functions and objects that are not supported by IE, and remove maxLength if it is set to `-1` as it prevents typing on IE.
=> Textfield fix ie

CHANGELOG.md, packages/notched-outline/src/mwc-notched-outline.scss, packages/textfield/src/mwc-textfield.scss
fixes #468 
This happens on older browsers. Not necessarily shady DOM. basically changed the root element from `display: flex-inline` to `display: flex`. Didn't seem to change anything adversely. Will check with internal screenshot testing after github approval.
Before:
After:
also fixes color of `mwc-textfield[required]` label asterisk when focused annd themed
=> fix extra spacing – older browsers

CHANGELOG.md, packages/textarea/src/mwc-textarea.scss
before:
after:
~awaiting confirmation that this is correct from design~
=> fix disabled styles on textarea

packages/dialog/package.json, packages/drawer/package.json
This version has a "module" field that resolves to ES2015 code (uses native ES2015 classes instead of transpiled). See https://github.com/WICG/inert/issues/136 for more context.
=> Bump wicg-inert polyfill to 3.0.0

packages/fab/src/mwc-fab-base.ts
fixes #484.
Please note that it seems as if `mdc-fab` is broken on canary:
https://invited-emu.glitch.me/
=> Update mwc-fab to MDC 4

packages/button/README.md
A contrived change to test our Copybara workflow.
=> Add some missing periods to the button README

packages/textfield/src/mwc-textfield-base.ts, packages/textfield/src/test/mwc-textfield.test.ts
Fixes #515
If we call `setValue` on the foundation when the value changes, all the base logic like positioning the floating label happens. there's already a check in the foundation for if the value is equal, so it won't double-update the input's value.
=> [mwc-textfield] call setValue when value changes

CHANGELOG.md, packages/notched-outline/README.md, packages/notched-outline/src/mwc-notched-outline.scss, packages/textarea/src/mwc-textarea.scss, packages/textfield/README.md, packages/textfield/src/mwc-textfield.scss
Fixes #460.
Fixes #544.
Refactored textfield styling to make more conceptual sense and collapse common selectors. Additionally, added the following css variables:
| Name                                              | Default               | Description
| ------------------------------------------------- | --------------------- |------------
| `--mdc-text-field-fill-color`                     | filled: `rgb(245, 245, 245)`, outlined: `transparent` | Color of the textfield's background fill.
| `--mdc-text-field-disabled-fill-color`            | filled: `rgb(250, 250, 250)`, outlined: `transparent` | Color of the textfield's background fill when disabled.
| `--mdc-text-field-ink-color`                      | `rgba(0, 0, 0, 0.87)` | Color of the input text.
| …
=> Textfield fill and ink styling

CHANGELOG.md, demos/dialog.html, packages/dialog/README.md, packages/dialog/src/mwc-dialog-base.ts, packages/dialog/src/mwc-dialog.scss, packages/dialog/src/test/mwc-dialog.test.ts
`Dialog.title` renamed to `Dialog.heading` and `--mdc-dialog-title-ink-color` renamed to `--mdc-dialog-heading-ink-color` as it caused clashes with `HTMLElement.prototype.title` causing a tooltip to appear everywhere.
Also quick fix to aria-labeledby and aria-describedby. Checked and works with mac voiceover
=> Dialog title -> heading + aria fix

packages/textarea/README.md
prefix of \ to render | properly in docs for validityTransform (otherwise interpreted as table column)
=> fixed error is validityTransform documentation

packages/textfield/README.md
prefixed the | in the Type docs for `Min`, `Max`, `Step` and `validityTransform` with \ to fix docs rendering issue: `number\|string`
=> fix rendering issue with min, max, step and validityTransform details

CHANGELOG.md, packages/dialog/README.md, packages/dialog/src/mwc-dialog-base.ts, packages/dialog/src/test/mwc-dialog.test.ts
Dialog will now search its distributed nodes' trees for focus. Needed for the following pattern:
```html
<my-dialog>
<input dialogInitialFocus>
#shadowRoot
<mwc-dialog>
<slot></slot>
</mwc-dialog>
</my-dialog>
```
=> search flattened distributed for focus

packages/ripple/src/mwc-ripple-base.ts, packages/ripple/src/test/mwc-ripple.test.ts
ripple won't be able to register clicks if the direct parent is a shadow root. This fixes this.
=> fix ripple shadow root

.gitignore, CHANGELOG.md, packages/slider/src/mwc-slider-base.ts
Fixed issue where slider when scrolled horizontally or when resized would not slide properly by calling layout (which gets bounding client rect) on touchstart or mousedown.
Also changelog for this and my other icon-button, ripple and snackbar PRs
Fixes #574
=> Slider scroll fix

CHANGELOG.md, packages/dialog/README.md, packages/dialog/src/mwc-dialog-base.ts
Added `show` and `close` methods to dialog because it is closer to `HTMLDialogElement` and because relying only on property runs into the following issue:
```ts
class MyElement extends LitElement {
@property() isDialogOpen = true;
render() {
return html`
<mwc-dialog .open=${this.isDialogOpen}></mwc-dialog>
`;
}
}
```
When user closes dialog with interaction, `isDialogOpen` will remain true while `mwc-dialog` remains false. If they want to open it again, they must call `this.requestUpdate('isDialogOpen')`.
=> Dialog show and close

.github/workflows/bump-mdc-deps.yml
I signed into the tedium-bot (Polymer automation account) GitHub page, created a personal access token, and added it to this repo's secrets as `TEDIUM_BOT_GITHUB_ACCESS_TOKEN`.
By using this token instead of the automatically populated `GITHUB_TOKEN` token, subsequent GitHub Actions will be allowed to run on the PR we create (i.e. tests).
See https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-536204092 for an explanation of this workaround.
=> Allow bump MDC deps action to trigger tests

packages/list/README.md, packages/list/src/mwc-check-list-item-base.ts, packages/list/src/mwc-list-base.ts, packages/list/src/mwc-list-foundation.ts, packages/list/src/mwc-list-item-base.ts, packages/list/src/mwc-radio-list-item-base.ts, packages/menu/src/mwc-menu-base.ts
Fixes #876 
Before:
you had to call `layout` every time you manually modified the DOM and set `<mwc-list-item selected>` outside of the initial render. The supported way before was to call `mwc-list.select(index)`.
caused issues where initial selection was made due to asynchronous calls. Also was not nice to deal with data-binding, especially with `mwc-select`
Now:
you can set `select` on an `mwc-list-item` and it updates `mwc-list` accordingly.
=> feat: list-item.selected will update list model

packages/textfield/src/mwc-textfield-base.ts
fixes #854
When you set `HTMLInputElement.value` in safari, it jumps the cursor to the end.
In this case, I prevented `mwc-textfield` from calling `render` when `value` is updated from `@input` as `render` will set `HTMLInputElement.value`.
Unfortunately, proper testing will require web driver which we do not have set up in any of our testing setups
=> fix(textfield): prevent safari caret jumping

CHANGELOG.md, scripts/sass-render/index.js
- Sass now has "default" imports that should handle `@material/theme` to
mean `@material/theme/_index.scss` that `node-sass-import` did not
understand
Fixes #850
=> Fix Sass "default" imports

packages/list/README.md
forgot to escape the `|` in our docs
=> docs: escape pipe in types

CHANGELOG.md, packages/list/src/mwc-list-foundation.ts, packages/menu/src/mwc-menu-base.ts, packages/select/README.md, packages/select/src/mwc-select-base.ts, packages/select/src/test/mwc-select.test.ts
fixes #875
possible large performance slowdown on first render in the following case:
```html
<mwc-select value="nonempty">
<div>Some assignedNode that is not a selectable item</div>
</mwc-select>
```
This slowdown was introduced because in the shady dom case, if you init with value, by first render callback you need your list items to be ready to select with `.value`. To prevent this wait on newer browsers, I limited it to the case where `value` was set, there are assigned nodes, but mwc-select does not know of any list-items. I felt that this would be a highly uncommon case as it is documented that setting `value` before the child is attached would not work as intended.
=> feat(select): select can now select via value prop

.github/workflows/tests.yml
Make it take less time to get to the quick, dumb checks
=> chore: move lint and format checks earlier in CI

CHANGELOG.md, packages/base/src/form-element.ts, packages/base/src/utils.ts, packages/checkbox/src/mwc-checkbox-base.ts, packages/checkbox/src/mwc-checkbox.scss, packages/ripple/src/mwc-ripple-base.ts, packages/ripple/src/ripple-directive.ts, packages/ripple/src/ripple-handlers.ts
Refactor checkbox to remove Foundation and ripple directive
- Remove checkbox adapter and foundation
- Replace ripple directive with lazy `mwc-ripple`
- Fix Closure Compiler renaming issues
Related #892
Related #894
Related #882
=> Refactor checkbox to remove Foundation and ripple directive

CHANGELOG.md, packages/button/src/mwc-button-base.ts, packages/button/src/mwc-button.scss, packages/button/src/mwc-button.ts, packages/button/src/test/mwc-button.test.ts, packages/ripple/src/mwc-ripple-base.ts, packages/ripple/src/mwc-ripple.scss
Refactor button
- Replace `ripple-directive` with lazy `mwc-ripple`
- Expose `--mwc-ripple-focus-opacity` and `--mwc-ripple-hover-opacity` for theming ripple focus and hover state
Related #894
Related #892
=> Refactor button

package-lock.json, package.json, packages/button/src/test/mwc-button.test.ts, packages/checkbox/src/test/mwc-checkbox.test.ts, packages/drawer/src/mwc-drawer-base.ts, packages/drawer/src/test/mwc-drawer.test.ts, packages/fab/src/test/mwc-fab.test.ts, packages/icon-button/src/test/mwc-icon-button.test.ts, packages/linear-progress/src/test/mwc-linear-progress.test.ts, packages/list/src/test/mwc-list.test.ts, packages/menu/src/test/mwc-menu.test.ts, packages/select/src/test/mwc-select.test.ts, packages/slider/src/test/mwc-slider.test.ts, packages/snackbar/src/test/mwc-snackbar.test.ts, packages/switch/src/test/mwc-switch.test.ts, packages/tab-bar/src/test/mwc-tab-bar.test.ts, packages/tab/src/test/mwc-tab.test.ts, test/src/util/helpers.ts
self-isolation lead to me writing some tests for you.
if they need changing any way just let me know.
cc @e111077 
I'll fix the lint error tomorrow, failing ci atm
=> add tests for several packages

test/src/benchmark/menu/basic.ts
basic benchmarking for menu. Would be great to have a nice wiz way to get rid of the `@property` on anchor since it's just passing it down to another element without any change and forcibly causing a rerender on boot. Perhaps `asyncQuery`?
=> perf(menu): benchmarking

packages/textfield/src/mwc-textfield-base.ts
Fix for #1158 
Tried to closely follow the implementation of the `step` attribute.
=> Added support for mwc-textfield size attribute

scripts/sass-render/index.js
This was causing problems where the first rule of the CSS output (with the Byte Order Marking in its prefix) would be discarded.
Closes #1275
=> fix(select): Strip byte order mark in CSS compilation

tsconfig.json
Internally, we disable a few checks in lit-analyzer for easier integration of other tools
`no-unknown-attribute` is disabled for teams to add app-specific attributes.
Incidentally, this also fixes our issue with https://github.com/runem/lit-analyzer/pull/107
=> Sync lit-analyzer settings with internal

scripts/bump-all-mdc-web-deps.ts
We'll remove this check once we've updated to the new M2 slider.
=> chore(slider): Stop updating MDC slider dep.

packages/circular-progress-four-color/package.json, packages/circular-progress/package.json, packages/dialog/package.json, packages/formfield/package.json, packages/linear-progress/package.json, packages/list/package.json, packages/notched-outline/package.json, packages/radio/package.json, packages/select/package.json, packages/switch/package.json, packages/tab-bar/package.json
Ensures that all modules that are consumed are also listed as dependencies in the manifest.
See: https://github.com/yarnpkg/berry/tree/master/packages/yarnpkg-doctor#no-unlisted-dependencies
Neglecting to declare these dependencies can (and already does) lead to them being unavailable in some module resolution mechanisms.
This issue manifests in errors such as:
```
../.yarn/cache/@material-mwc-select-npm-0.17.2-d80ce2ad81-36d9783eac.zip/node_modules/@material/mwc-select/mwc-select-base.d.ts:22:28 - error TS2307: Cannot find module '@material/list/typeahead.js' or its corresponding type declarations.
22 import * as typeahead from '@material/list/typeahead.js';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../.yarn/cache/@material-mwc-select-npm-0.17.2-d80ce2ad81-36d9783eac.zip/node_modules/@material/mwc-se …
```
=> fix: undeclared indirect dependencies

README.md
Adding a link to provide more direct access to theming.
It also makes it more prominent.
=> fix(docs): add theming guide to root README.md

package-lock.json, package.json, packages/checkbox/test/mwc-checkbox.test.ts, packages/menu/test/mwc-menu.test.ts, packages/slider/test/mwc-slider.test.ts, packages/snackbar/test/mwc-snackbar.test.ts, packages/switch/test/mwc-switch.test.ts, packages/tab/test/mwc-tab.test.ts, test/src/util/helpers.ts
a while ago i removed sinon and left over some of our own helpers to deal with that.
this just removes the `Fake` i added and uses a dependency instead so we have less to maintain. timers are still mocked by ourselves though.
if you prefer having your own implementation, thats fair enough just let me know. 
have left the PR as draft for now just in case CI has different test results than i had locally.
=> remove Fake in place of module

.github/workflows/tests.yml
Moved lint check to run in separate workflow. `lint` workflow run will be non-blocking for changes synced from CL to PR.
=> build: Move lint test to separate workflow run

CHANGELOG.md, packages/list/mwc-list-base.ts, packages/list/mwc-list-item-base.ts, packages/list/test/mwc-list.test.ts
when removing an item.
Closes #1927 
See my remarks blow regarding the outcome of this performance improvement, and proposed changes to this PR.
=> Debounce the layout function in the list component

packages/circular-progress-four-color/README.md
Fix typo in circular-progress-four-color component README.md.
=> Fix typo in circular-progress-four-color component README.md.

karma.conf.js, packages/drawer/test/mwc-drawer.test.ts
Bumped safari versions, for some reason transitionend does not fire on safari 13 twice in a row. Behavior seems correct, but the browser is just not firing the event. Safari 13-specific workaround implemented
fixes #1869
=> chore: bump safari test versions & fix test

packages/circular-progress-four-color/test/mwc-circular-progress-four-color.test.ts, packages/circular-progress/test/mwc-circular-progress.test.ts
i remember we were moving tests towards this structure so figured i'd do a few more.
i've updated the circular progress bar and the four colour one, too. now we cover the defaults and also the behaviour of setting out of bounds progress percentages.
let me know if this is fine & still the way you're writing them
cc @e111077
=> chore: update circular progress tests to use fixtures

packages/fab/test/mwc-fab.test.ts
have done the same i did with the other tests:
- moved them to use fixtures
- added assertions for the initial values
- added tests for `reducedTouchTarget`
cc @e111077
=> test(fab): rework tests to use fixtures

README.md
Web Dev Server is the successor to es-dev-server.
https://modern-web.dev/docs/dev-server/overview/
=> Update README to use Web Dev Server

package.json
External typescript lint (including format lint) conflicts with internal TS lint and produces different results. This impedes devex because the turn around time to validate lint is slow (i.e., waits till GitHub Action is complete), also has no integration to internal review tool.
All the code that gets checked-in should be tested internally.
=> chore: Remove typescript lint from GitHub tests

package.json
The copybara bot reverted the new Sass version from #2475 in #2473, but only in `package.json`.
=> Restore newer version of Sass.

packages/linear-progress/package.json
`mwc-base` is used in linear progress, but was missing from its dependencies.
=> Add `mwc-base` dependency to linear progress

packages/radio/mwc-radio-base.ts
This was breaking some users that didn't install ripple on their own project as TS will remove the ripple type import
=> fix(radio): add ripple side effect import

.github/workflows/tests.yml
Similar to MDC-Web removing any external lint checks which are redundant (and potentially out of sync) with internal lint checks.
Every change should be tested internally before commit.
=> chore: Remove lint checks from Github Action tests

.github/workflows/auto-format.yml, .github/workflows/bump-mdc-deps.yml, .github/workflows/deploy-demos.yml, .github/workflows/release-canary.yml, .github/workflows/tests.yml, package.json, packages/button/_button.scss
- Fixes some more spots where invalid `calc` syntax causes a compilation error after a Sass minor version bump to v1.41. See also https://github.com/material-components/material-components-web/pull/7393 and https://github.com/material-components/material-components-web/pull/7402 which fix the other spots.
- Until https://github.com/material-components/material-components-web/pull/7402 is published to NPM, we'll need to pin this repo's Sass version to `~1.34.1`, because this repo directly compiles sass files from the MDC packages.
- Also bumps the Node version in CI from 12 to 14, since 14 is now the active LTS version.
=> More sass 1.41 compat fixes

packages/icon-button/mwc-icon-button-base.ts
Since flex is now used for alignment, the `i` element, that is always rendered even when not used, now messes the alignment up when the `slot` is used.
This PR fixes that by not rendering the `i` element when it is not used.
=> fix(mwc-icon-button) Fix alignment when slot is used

packages/base/package.json
In https://github.com/material-components/material-web/commit/6278ee5df98ca7eae0d694e58b052fdbf4b0519d we aligned on lit^2.0.0 but kept an explicit version of @lit/reactive-element for no apparent good reason. This just cleans it up
=> chore: remove hardcoded lit/reactive-element version

packages/list/package.json, packages/menu/package.json
Hi there!
This change adds the repository property to your package.json file(s). Having this available provides a number of benefits to security tooling. For example, it allows for greater trust by checking for signed commits, contributors to a release and validating history with the project. It also allows for comparison between the source code and the published artifact in order to detect attacks on authors during the publication process.
We validate that we're making a PR against the correct repository by comparing the metadata for the published artifact on [npmjs.com](www.npmjs.com) against the metadata in the package.json file in the repository.
This change is provided by a team at Microsoft -- we're happy to answer any questions you may have. (Members of this team include …
=> Update package.json to include the repository

.gitignore, package.json
Uses https://github.com/google/wireit to update the 3rd party build to support incremental compile, watch mode (`npm run build --watch`), caching, etc.
=> Add wireit build config

button/lib/button.ts, iconbutton/lib/icon-button.ts
Fixes #3245 by adding support for the `aria-expanded` attribute in the same manner as `aria-haspopup`.
Note this is identical to #3398 minus the docs since they don't exist yet.
=> feat(button,iconbutton): add support for aria-expanded to buttons

docs/components/button.md
Update `button.md` doc to comply with the new syntax.
The attribute `label` was removed from `v1.0.0-pre.7`.
=> docs: update button docs with label change

chips/lib/_assist-chip.scss, chips/lib/_suggestion-chip.scss
Refer https://github.com/material-components/material-web/commit/7ce0e256b2432f3a5f696d75fa64010786bd79d7#diff-fb7354e17296558d8fed9fd8a2b78dd068cb98a828b9e488ba2d95ef3880807aL41 and https://github.com/material-components/material-web/commit/d029b634c7392947f4edfa27f6218be486447de5#diff-2f432356e56de01d1beaa79f7dc17c5e259bffbaf82730658f92d21767e2bd84R40
=> fix(chips): incorrect shape custom property names

docs/quick-start.md
The current docs provide a label property that does not work, so this doc changes that to text inside the element
=> docs: fix button labels

catalog/package.json, package-lock.json, package.json
We have to do this externally because we don't sync the package-lock internally and CI runs `npm ci` which breaks due to a mismatch between package.json and package-lock.json
=> build: setup the npm workspace for the catalog

list/lib/listitem/list-item-only.ts
The `noninteractive` property decorator needs the `type` option set to `Boolean` or else the attribute is ignored.
=> fix(list-item): infer noninteractive property type

dialog/lib/dialog.ts
This change fixes https://github.com/material-components/material-web/issues/4244
`escapeKeyAction` set to an empty value should prevent the dialog from closing when user presses the escape key on their keyboard.
=> fix(dialog): prevent dialog from closing when escapeKeyAction is empty

.npmignore, package.json
fixes #4446
Tested locally with `npm publish --dry-run`
Recommend a bugfix deploy after.
=> build: npmignore node modules from catalog

package-lock.json
lit ssr update includes a fix for defer-hydration
https://github.com/lit/lit/issues/3939
=> build: update dependencies

.gitignore, catalog/package.json, catalog/src/types/is-land.d.ts, catalog/tsconfig.json
This enables typechecking on the catalog so that we catch type build issues in CI next time. Type issues didn't break before since we run our code through esbuild, and it was disabled because of some weird 11ty issues that are fixed in this CL
This should prevent issues like b/288481318 from passing by again
Depends on #4489 to merge first
=> build(catalog): re-enable catalog typechecking

package-lock.json, package.json
The `"."` in workspaces config seems to create an infinite recursive symlink as seen here https://github.com/google/wireit/issues/790
It looks unnecessary to include the root directory in the workspaces config. No commands in the repo currently use the `--workspace` or `--workspaces` flag for npm commands so those commands should not be affected.
If there were `--workspaces` flags meant to run a command for all workspace directories, the root directory can be included by `--include-workspace-root` flag as well. https://docs.npmjs.com/cli/v8/commands/npm-run-script#include-workspace-root
`@material/web` use within the `catalog` workspace still correctly resolves to the root package with the reference, and does not install its own copy from npm.
=> fix(repo): remove "." from workspace config

package.json
This will avoid wireit looping through the `@material/web` symbolic link in watch mode.
=> fix: wireit sass watch memory leak

chips/lib/filter-chip.ts, chips/lib/input-chip.ts
In a chip set context, there are currently no way to query selected chips from the outside  
(e.g. `queryAll('md-filter-chip[selected]')`).
This PR solves that problem.
=> chore(chip): reflect filter chip selected value

list/lib/listitemlink/list-item-link-only.ts
- Adding `type: Boolean` to `noninteractive` property.
- Prevent focus ring to appear when `noninteractive` is set to `true`
=> fix(list): infer noninteractive property type

radio/lib/radio.ts
Fix a Safari-related bug, causing radio button to fail to render properly.
Pretty naive implementation resolving #4531.
=> fix(radio): ensure unique maskId for radio SVG mask. Fix #4531

radio/lib/single-selection-controller.ts
As click events propagates, triggering a click action on radio-button creates potential unwanted side-effect (for instance, it will activate ripple effect of parent container like `md-list-item`).
Here, I propose to revert #4518 to its original form - without 3436d023a0caca9181e65a7a1189f3fda694f840.
See https://github.com/material-components/material-web/pull/4518#issuecomment-1625625170 for justification.
=> fix(radio): prevent triggering click action on radio keyboard navigation

tokens/_md-comp-outlined-segmented-button.scss
It fixes the height of the container (which is of 40px in the specifications).
=> fix(segmentedbutton): add back container height token

list/internal/listitem/_list-item.scss
Hey there!
Excited to be contributing to this repository for the first time!
So, in this pull request, I tackled an issue with overflowing content in the list-item's body. The fix was pretty straightforward - I set `max-width: 100%` to the list-item's body element. To make things even better, I also got rid of the `display: flex` from `label-text`, which wasn't doing much except making truncation more complicated. I mean, it's just text inside label-text, so no need for flex, right?
Here's how it looks like:
Many thanks for checking this out! Looking forward to your review!
Cheers,
David
=> fix(list): list item body overflow issue

labs/badge/internal/_badge.scss
I noticed the text in the badge was not properly centered. This is the first solution that came to my mind, any thought on that?
=> fix(badge): center align value text

textfield/internal/text-field.ts
=> chore(text-field): add autocomplete attribute

docs/components/button.md
On https://material-web.dev/components/button/, both the icons are at the front. The correct attribute is `trailing-icon`. Source code:
https://github.com/material-components/material-web/blob/573caaee1b7fe64b57b84e2b287b6c5c74666de1/button/internal/button.ts#L59
=> docs: corrected button trailing-icon

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation-bug.yaml
This provides a scaffold for folk to fill in bug reports.
This PR adds the following when someone clicks on "file an issue":
- Bug template, which tries to capture many details about a bug.
- Documentation bug template, for documentation issues and issues with `material-web.dev`.
- "Questions, Help, and Advice" section that links to https://github.com/material-components/material-web/discussions
- "💬 Chat" section that links to the Discord.
This was not tested. But it was closely based on https://github.com/aomarks/issue-template-test/tree/main/.github/ISSUE_TEMPLATE
I omitted "feature-requests" template because I wasn't sure how to structure it. I also omitted a free-form "other" template that allows someone a little less structure if needed. In the short term these can be handled in …
=> chore: add GitHub issue templates for bugs & links to docs and community

labs/item/internal/_item.scss
fixes https://github.com/material-components/material-web/issues/5011
I found this solution, which is excluding the start slot from this css block, the start slot generally will contain icons or similar square-ish elements (e.g. checkbox) so this rule doesn't really need to be applied on this one.
Also, users can always set `overflow: hidden` manually on the element if they want to.
**One rock two birds!**
This PR also fixes another problem that I was about to report, if checkbox is used as a `start` slot the focus ring is not appearing. I just realize the reason the focus ring is not appearing is because the overflow is hidden, it makes sense.
=> fix(md-item): exclude start slot from hidden overflow

catalog/site/css/md-layout.css
Elements are not properly centered in blockquotes I noticed:
=> fix(catalog): center items in blockquotes

docs/components/progress.md, progress/internal/linear-progress.ts
Currently the doc says `<md-linear-progress>`'s `buffer`: 
> Buffer amount to display, a fraction between 0 and 1.
This is incorrect. It should be between 0 and **`max`** like `value`. See [Lit playground](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQgXCJAbWF0ZXJpYWwvd2ViL2FsbFwiOyJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8bWQtbGluZWFyLXByb2dyZXNzIG1heD1cIjEwMFwiIHZhbHVlPVwiNTBcIiBidWZmZXI9XCIwLjc1XCI-PC9tZC1saW5lYXItcHJvZ3Jlc3M-XG4gIFxuICA8aHIgLz5cbiAgXG4gIDxtZC1saW5lYXItcHJvZ3Jlc3MgbWF4PVwiMTAwXCIgdmFsdWU9XCI1MFwiIGJ1ZmZlcj1cIjc1XCI-PC9tZC1saW5lYXItcHJvZ3Jlc3M-ICBcbjwvYm9keT5cbiJ9LHsibm …
=> docs(progress): corrected buffer value description

tabs/internal/_tab.scss
The elevation of a tab is displayed in square shape:
This fix is applying the shape to `md-elevation` element as well:
=> fix(tabs): apply shape to tab elevation

textfield/internal/text-field.ts
Currently the `cols` attribute is not properly relayed to the internal textarea element (https://lit.dev/playground/#gist=2f70901d7332c1885824046a20046596)
This change adds the possibility to use the `cols` attribute.
=> chore(textfield): Add cols attribute to type textarea

tabs/internal/tabs.ts
Fixes TypeError "smooth" | "instant" not compatible with ScrollBehavior type
=> fix(tabs): type const -> ScrollBehavior

progress/internal/_circular-progress.scss
=> fix(progress): circular progress stretched in flex column display

docs/components/text-field.md
Fix the URL to material-web.dev
=> docs: broken text field link

dialog/internal/_dialog.scss
Fixes #5182
The old version hide the md-icon in a md-dialog because of aggressive css rebooting of bootstrap.
My fix is to make the md-icon in md-dialog use margin-top instead of padding-top, and it fix the problem in my browser.
Thank to @christophe-g and @asyncLiz. They give me the opportunity to figure it out and to contribute this PR.
=> fix(dialog): use margin instead of padding for icon

docs/components/icon.md, icon/internal/_icon.scss, tokens/_md-comp-icon.scss
Fixes #5055 
In the old version, the size was controlled by a css variable `font-size: var(--mdc-icon-size, 24px);` Our development is heavily dependent on this to control the size, and the quickest update route is to get back the `md-icon-size` `token`.
Addresses https://github.com/material-components/material-web/issues/5055 see as well https://github.com/material-components/material-web/issues/5055#issuecomment-1791443215
=> feat(icon): add `--md-icon-size` token

menu/internal/_menu.scss
fixes: https://github.com/material-components/material-web/issues/5226
=> fix(menu): prevent native popover text color from overriding menu surface text color

progress/internal/linear-progress.ts
Progress has an infinite animation on `<div class="dots">`. `.dots` is only visible when `value` < `max` or `buffer` < `max`. But the animation runs in any case.
Related comment:  https://github.com/material-components/material-web/issues/5251#issuecomment-1858294982
=> perf(progress): remove hidden animation when dots are not visible

package.json
=> fix(testing): add testing folder to npm package

dialog/demo/demo.ts, dialog/demo/stories.ts, dialog/internal/dialog.ts
Fixes https://github.com/material-components/material-web/issues/5465
=> feat(dialog): add `quick` property to skip animations

progress/internal/linear-progress.ts
Fix #5251 .
```html
<md-linear-progress value="10" max="100"></md-linear-progress>    
<md-linear-progress value="10" buffer="50" max="100"></md-linear-progress>
```
=> fix(progress): progress buffer defaults to 0

switch/internal/switch.ts, switch/internal/switch_test.ts
Fixes https://github.com/material-components/material-web/issues/5486
=> fix(switch): `selected` state is updated during input event

slider/internal/_slider.scss
Fixes #5518
I have changed md-slider track's css property background-color to background, so now it is possible to set a gradient as bg of slider's track. Example:
=> fix(slider): support linear-gradient track background colors

docs/theming/README.md
There aren't CSS vars prefixed with `--md-sys--typograph`. The correct prefix is `--md-sys--typescale`. See https://github.com/material-components/material-web/blob/main/tokens/_md-sys-typescale.scss#L138.
The "Typography" heading could also be renamed to "Typescale" for consistency with how the section is named in the [Typography page](https://material-web.dev/theming/typography/#typescale).
=> docs: fix typo on theming docs

textfield/internal/text-field.ts
Add name attribute to input and textarea elements created by the text-filed element. 
This enables autocomplete to work int he browser even if a form is not used.
Discussed in issue #4589
=> fix(textfield): browser autocomplete works outside of a form

catalog/package.json, package-lock.json
This is needed to fix the broken tasks for https://github.com/material-components/material-web/pull/5666
=> chore(catalog): fix `@material/web` dependency restriction for 2.0

dialog/internal/dialog.ts
Hey, 
I've been trying to get Material Components to work in NextJS SSG. All other components work fine [except for Dialog](https://github.com/grayhatdevelopers/material-web-react/blob/main/apps/demo/src/app/page.tsx#L14), which throws the error `document is not defined`.
Upon inspection, the reason is because Dialog uses document.treeWalker upon initialization. I've added a check to initialize it as an empty object typecasted to TreeWalker, so that it works fine in SSG.
Tested, works ok. However, I'd love to know if there's a better way, instead of typecasting.
=> feat: check for server before creating treewalker from document

catalog/src/components/copy-code-button.ts
Fixes #5696
**Description:**
This pull request addresses issue #5696, where the check mark indicating a successful clipboard action did not appear when clicking the clipboard icon in the Material Web UI.
**Changes Made:**
- Updated the icon name from `checkmark` to `check` in the `slot="selected"` for the `md-icon-button` component.
**Details:**
The issue occurred because the `md-icon` component was using an incorrect icon name for the selected state. By changing the icon name to `check`, the check mark now correctly displays upon clicking the clipboard icon, providing the expected visual feedback.
**Testing:**
- Verified that the check mark appears correctly after clicking the clipboard icon.
- Ensured that no other functionalities were affected by this change.
**Related Issue:**
- Fixes …
=> fix(catalog): clipboard check copy icon not showing

labs/badge/internal/_badge.scss, labs/navigationbar/internal/_navigation-bar.scss, labs/navigationtab/internal/_navigation-tab.scss, labs/segmentedbutton/internal/_outlined-segmented-button.scss
I found that some components in the labs folder had duplicate CSS variables (includes badge, navigationbar, navigationtab, segmentedbutton) , like this:
After I compile the component style separately through sass:
`npx sass ./labs/navigationbar/internal/navigation-bar-styles.scss ./o.css`
This is because of unnecessary prefixes in these styles:
```scss
@each $token, $value in $tokens {
// We need to delete "var(--md-navigation-bar-#{$token}, "
//--_#{$token}: var(--md-navigation-bar-#{$token}, #{$value});
--_#{$token}: #{$value};
}
```
After repair:
=> fix(labs): remove unnecessary CSS duplication variables of components in labs

radio/internal/_radio.scss, radio/internal/radio.ts
=> fix(radio): change touch target to fix blocked aria-hidden on an <input> element error

docs/components/button.md
<details open>
<summary><b><em>Actual button/internal/button.ts hasIcon property declaration:</em></b></summary>
```typescript
/**
* Whether to display the icon or not.
*/
@property({type: Boolean, attribute: 'has-icon', reflect: true}) hasIcon = false;
```
</details>
While the code for the button with an icon in the catalog displays correctly, I believe that checking the code in the stories or Dev Tools might mislead users. This has been my experience.
=> fix(catalog): add hyphen to md-elevated-button attribute

button/internal/button.ts, chips/internal/assist-chip.ts, iconbutton/internal/icon-button.ts
Adds support for specifying a filename when downloading a file using a link button.
Example usage:
```html
<md-filled-tonal-button href="#" download="example-file.pdf">
Download File (PDF, 1.5 MB)
</md-filled-tonal-button>
```
=> feat(button,chips,iconbutton): add download filename support for links

dialog/internal/dialog.ts
Fixes #5777
[md-dialog: handleSubmit fails with a <input name="method" /> as dialog form child](https://github.com/material-components/material-web/issues/5777)
=> fix(dialog): control with name="method" no longer breaks submit

textfield/internal/text-field.ts
This PR adds a new method to the `TextField` class in `textfield/internal/text-field.ts` to support calling of the `showPicker` method, which allows the browser picker to be shown for input elements of type "date", "time", etc.
=> feat(textfield): add showPicker method

catalog/site/_includes/default.html
Incorporating a CSS rule to mitigate [First Contentful Paint](https://web.dev/articles/fcp) (FCP) layout shifts on non-DSD-native user agents. This explicitly leverages the `dsd-pending` attribute, which is added in the default template and subsequently removed post-DOM hydration by the `src/ssr-utils/dsd-polyfill.ts`. This ensures a controlled initial rendering state, preventing unstyled or unhydrated content from momentarily disrupting visual stability.
=> fix(catalog): hide body if dsd-pending

catalog/site/_includes/layouts/components.html
This `{% if not ssrOnly %}` ... `{% else %}` ... `{% endif %}` is a conditional statement that checks if a variable named `ssrOnly` is `false`.
If it is `false` then the JavaScript is loaded and hydrated onto the components nested inside on an idle callback via the `<lit-island>` utility.
Essentially, a `<lit-island>` tag is a wrapper or a container designed to encapsulate other Lit components and control when and how they are hydrated (become interactive) on the client side.
This PR fixes the layout structure to provide hydration or not depending on the `ssrOnly` attribute.
=> fix(catalog): hydrate CSR component pages

catalog/site/css/global.css
padding: block 2px; isn't valid css. It's padding-block: 2px;
=> chore(catalog): fix padding block in global.css for md-item
